name: "Deploy to S3"
description: "Deploys to s3 bucket, it assumes a smile IAM role. Must be run on internal runners with the `category-applications` label."
inputs:
  s3_bucket:
    description: "S3 bucket were the assets will be uploaded"
    required: true
  source_path:
    description: "Resources path to upload to s3"
    required: true
  short_environment:
    description: "Environment short-form as used in Smile's infrastructure-live repo. One of `dev`, `stage`, `prod`"
    required: true
  release_version:
    description: "The new release version of assets that should be deployed."
    required: true

runs:
  using: composite
  steps:
    - name: Assume IAM Role
      shell: bash
      run: |
        export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-role \
          --role-arn "arn:aws:iam::${{ fromJson('{"dev": "307739032832", "stage": "389299793054", "prod": "964498696771"}')[inputs.short_environment] }}:role/allow-auto-deploy-from-other-accounts" \
          --role-session-name AWSCLI-Session \
          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
          --output text))
        aws s3 cp ${{ inputs.source_path }} s3://${{ inputs.s3_bucket }}/${{ inputs.release_version }} --recursive
